{{ config(materialized = 'table', alias = 'demographics') }}

SELECT DISTINCT
	_0_a_token AS survey_id,
	to_timestamp(_0_d_data_hora_envio, 'DD/MM/YYYY HH24:MI:SS') AS dt_submitted,
	cast(_1_a_idade as integer) AS age,
	coalesce(_1_a_1_faixa_idade, 'No answer') AS age_range,
	coalesce(_1_b_genero, 'No answer') AS gender,
	coalesce(_1_c_cor_raca_etnia, 'No answer') AS race,
	coalesce(_1_d_pcd, 'No answer') AS pwd,
	coalesce(_1_e_experiencia_profissional_prejudicada, 'No answer') AS carrer_prejudicated,
	cast(_1_e_1_nao_acredito_que_minha_experiencia_profissional_seja_afe as boolean) AS not_prejudicated,
	cast(_1_e_2_sim_devido_a_minha_cor_raca_etnia as boolean) AS prejudicated_race,
	cast(_1_e_3_sim_devido_a_minha_identidade_de_genero as boolean) AS prejudicated_gender,
	cast(_1_e_4_sim_devido_ao_fato_de_ser_pcd as boolean) AS yes_pwd,
	coalesce(_1_f_aspectos_prejudicados, 'No answer') AS prejudicated_aspects,
	cast(_1_f_1_quantidade_de_oportunidades_de_emprego_vagas_recebidas as boolean) AS prejudicated_opportunities,
	cast(_1_f_2_senioridade_das_vagas_recebidas_em_relacao_a_sua_experie as boolean) AS prejudicated_senior_roles,
	cast(_1_f_3_aprovacao_em_processos_seletivos_entrevistas as boolean) AS prejudicated_interviews,
	cast(_1_f_4_oportunidades_de_progressao_de_carreira as boolean) AS prejudicated_carreer_progression,
	cast(_1_f_5_velocidade_de_progressao_de_carreira as boolean) AS prejudicated_carreer_progression_velocity,
	cast(_1_f_6_nivel_de_cobranca_no_trabalho_stress_no_trabalho as boolean) AS prejudicated_stress,
	cast(_1_f_7_atencao_dada_pelas_pessoas_diante_das_minhas_opinioes_e_ as boolean) AS prejudicated_attention,
	cast(_1_f_8_relacao_com_outras_pessoas_da_empresa_em_momentos_de_tra as boolean) AS prejudicated_relation,
	cast(_1_f_9_relacao_com_outras_pessoas_da_empresa_em_momentos_de_int as boolean) AS prejudicated_relation_off,
	cast(_1_g_vive_no_brasil AS boolean) AS brazil_resident,
	coalesce(_1_h_pais_onde_mora, 'No answer') AS country_resident,
	coalesce(_1_i_estado_onde_mora, 'No answer') AS state_resident,
	coalesce(_1_i_1_uf_onde_mora, 'No answer') AS uf_state_resident,
	coalesce(_1_i_2_regiao_onde_mora, 'No answer') AS region_resident,
	cast(_1_j_vive_no_estado_de_formacao AS boolean) AS education_state_resident,
	coalesce(_1_k_estado_de_origem, 'No answer') AS state_born,
	coalesce(_1_k_1_uf_de_origem, 'No answer') AS uf_state_born,
	coalesce(_1_k_2_regiao_de_origem, 'No answer') AS region_born,
	coalesce(_1_l_nivel_de_ensino, 'No answer') AS education_level,
	coalesce(_1_m_area_de_formacao, 'No answer') AS education_area,
	current_timestamp AS updated_at
FROM
	{{ source('state_of_data', 'sheets_state_of_data')}}
