{{ config(materialized = 'table', alias = 'demographics') }}

SELECT DISTINCT
	_0_a_token AS survey_id,
	to_timestamp(_0_d_data_hora_envio, 'DD/MM/YYYY HH24:MI:SS') AS dt_submitted,
	cast(_1_a_idade as integer) AS age,
	_1_a_1_faixa_idade AS age_range,
	_1_b_genero AS gender,
	_1_c_cor_raca_etnia AS race,
	_1_d_pcd AS pwd,
	coalesce(_1_e_experiencia_profissional_prejudicada, 'No answer') AS carrer_prejudicated,
	coalesce(_1_e_1_nao_acredito_que_minha_experiencia_profissional_seja_afe, 'No answer') AS not_prejudicated,
	coalesce(_1_e_2_sim_devido_a_minha_cor_raca_etnia, 'No answer') AS prejudicated_race,
	coalesce(_1_e_3_sim_devido_a_minha_identidade_de_genero, 'No answer') AS prejudicated_gender,
	coalesce(_1_e_4_sim_devido_ao_fato_de_ser_pcd, 'No answer') AS yes_pwd,
	coalesce(_1_f_aspectos_prejudicados, 'No answer') AS prejudicated_aspects,
	coalesce(_1_f_1_quantidade_de_oportunidades_de_emprego_vagas_recebidas, 'No answer') AS prejudicated_opportunities,
	coalesce(_1_f_2_senioridade_das_vagas_recebidas_em_relacao_a_sua_experie, 'No answer') AS prejudicated_senior_roles,
	coalesce(_1_f_3_aprovacao_em_processos_seletivos_entrevistas, 'No answer') AS prejudicated_interviews,
	coalesce(_1_f_4_oportunidades_de_progressao_de_carreira, 'No answer') AS prejudicated_carreer_progression,
	coalesce(_1_f_5_velocidade_de_progressao_de_carreira, 'No answer') AS prejudicated_carreer_progression_velocity,
	coalesce(_1_f_6_nivel_de_cobranca_no_trabalho_stress_no_trabalho, 'No answer') AS prejudicated_stress,
	coalesce(_1_f_7_atencao_dada_pelas_pessoas_diante_das_minhas_opinioes_e_, 'No answer') AS prejudicated_attention,
	coalesce(_1_f_8_relacao_com_outras_pessoas_da_empresa_em_momentos_de_tra, 'No answer') AS prejudicated_relation,
	coalesce(_1_f_9_relacao_com_outras_pessoas_da_empresa_em_momentos_de_int, 'No answer') AS prejudicated_relation_off,
	cast(_1_g_vive_no_brasil AS boolean) AS brazil_resident,
	_1_h_pais_onde_mora AS country_resident,
	_1_i_estado_onde_mora AS state_resident,
	_1_i_1_uf_onde_mora AS uf_state_resident,
	_1_i_2_regiao_onde_mora AS region_resident,
	cast(_1_j_vive_no_estado_de_formacao AS boolean) AS education_state_resident,
	coalesce(_1_k_estado_de_origem, 'No answer') AS state_born,
	coalesce(_1_k_1_uf_de_origem, 'No answer') AS uf_state_born,
	coalesce(_1_k_2_regiao_de_origem, 'No answer') AS region_born,
	_1_l_nivel_de_ensino AS education_level,
	_1_m_area_de_formacao AS education_area,
	current_timestamp AS updated_at
FROM
	{{ source('state_of_data', 'sheets_state_of_data')}}
