{{ config(materialized = 'table', alias = 'work') }}

SELECT DISTINCT
    	_0_a_token AS survey_id,
	to_timestamp(_0_d_data_hora_envio, 'DD/MM/YYYY HH24:MI:SS') AS dt_submitted,
	coalesce(_2_a_situacao_de_trabalho, 'No answer') AS work_situation,
	coalesce(_2_b_setor, 'No answer') AS company_area,
	coalesce(_2_c_numero_de_funcionarios, 'No answer') AS number_of_workers,
	cast(_2_d_atua_como_gestor AS boolean) AS manager_role,
	coalesce(_2_e_cargo_como_gestor, 'No answer') AS manager_role_name,
	coalesce(_2_f_cargo_atual, 'No answer') AS current_role_work,
	coalesce(_2_g_nivel, 'No answer') AS role_level,
	coalesce(_2_h_faixa_salarial, 'No answer') AS salary_range,
	coalesce(_2_i_tempo_de_experiencia_em_dados, 'No answer') AS years_data_experience,
	coalesce(_2_j_tempo_de_experiencia_em_ti, 'No answer') AS years_it_experience,
	cast(_2_k_satisfeito_atualmente as boolean) AS current_satisfied,
	coalesce(_2_l_motivo_insatisfacao, 'No answer') AS reason_insatisfied,
	cast(_2_l_1_remuneracao_salario as boolean) AS insatisfied_salary,
	cast(_2_l_2_beneficios as boolean) AS insatisfied_benefits,
	cast(_2_l_3_proposito_do_trabalho_e_da_empresa as boolean) AS insatisfied_purpose,
	cast(_2_l_4_flexibilidade_de_trabalho_remoto as boolean) AS insatisfied_remote_work,
	cast(_2_l_5_ambiente_e_clima_de_trabalho as boolean) AS insatisfied_enviroment_work,
	cast(_2_l_6_oportunidade_de_aprendizado_e_trabalhar_com_referencias as boolean) AS insatisfied_learning_work,
	cast(_2_l_7_oportunidades_de_crescimento as boolean) AS insatisfied_growth,
	cast(_2_l_8_maturidade_da_empresa_em_termos_de_tecnologia_e_dados as boolean) AS insatisfied_data_maturity,
	cast(_2_l_9_relacao_com_os_gestores_e_lideres as boolean) AS insatisfied_manager_relationship,
	cast(_2_l_10_reputacao_que_a_empresa_tem_no_mercado as boolean) AS insatisfied_company_reputation,
	cast(_2_l_11_gostaria_de_trabalhar_em_outra_area as boolean) AS insatisfied_another_area,
	coalesce(_2_m_participou_de_entrevistas_ultimos_6_m, 'No answer') AS interview_participation_l6m,
	coalesce(_2_n_planos_de_mudar_de_emprego_6_m, 'No answer') AS work_change_plans,
	coalesce(_2_o_criterios_para_escolha_de_emprego, 'No answer') AS work_requirements_criteria,
	cast(_2_o_1_remuneracao_salario as boolean) AS work_req_salary,
	cast(_2_o_2_beneficios as boolean) AS work_req_benefits,
	cast(_2_o_3_proposito_do_trabalho_e_da_empresa as boolean) AS work_req_purpose,
	cast(_2_o_4_flexibilidade_de_trabalho_remoto as boolean) AS work_req_remote,
	cast(_2_o_5_ambiente_e_clima_de_trabalho as boolean) AS work_req_enviroment,
	cast(_2_o_6_oportunidade_de_aprendizado_e_trabalhar_com_referencias as boolean) AS work_req_learning,
	cast(_2_o_7_plano_de_carreira_e_oportunidades_de_crescimento as boolean) AS work_req_carreer_plan,
	cast(_2_o_8_maturidade_da_empresa_em_termos_de_tecnologia_e_dados as boolean) AS work_req_data_maturiry,
	cast(_2_o_9_qualidade_dos_gestores_e_lideres as boolean) AS work_req_manager_quality,
	cast(_2_o_10_reputacao_que_a_empresa_tem_no_mercado as boolean) AS work_req_company_reputation,
	coalesce(_2_q_empresa_passou_por_layoff_em_2024, 'No answer') AS company_layoff_2024,
	coalesce(_2_r_modelo_de_trabalho_atual, 'No answer') AS current_work_policy,
	coalesce(_2_s_modelo_de_trabalho_ideal, 'No answer') AS ideal_work_policy,
	coalesce(_2_t_atitude_em_caso_de_retorno_presencial, 'No answer') AS action_if_rto,
	current_timestamp AS updated_at
FROM
	{{ source('state_of_data', 'sheets_state_of_data')}}
